language: node_js
node_js:
  - "stable"
install:
  - npm install -g codecov
  - npm install -g gulp-cli
  - npm install
services:
  - postgresql
env:
  global:
    - PORT=8000
    - DATABASE_NAME=sequelize
    - DATABASE_USER=postgres
    - DATABASE_PASSWORD=postgres
    - JWT_SECRET=verysecretkey&*()=%
before_script:
  - psql -c 'create database sequelize;' -U postgres
  - psql -c "CREATE USER root WITH PASSWORD 'postgres';" -U postgres
script:
  - npm test
  - codecov


