language: node_js
node_js:
  - "stable"
install:
  - npm install -g codecov
  - npm install -g gulp-cli
  - npm install
services:
  - postgresql
env:
before_script:
  - psql -c 'create database more_recipes_test;' -U postgres
  - psql -c "CREATE USER root WITH PASSWORD 'password';" -U postgres
script:
  - npm test
  - codecov


